-- ============================================================
-- TMS Step 1 — schema, RLS, numbering. NZ-only. All additive.
-- Applied live to cpnkudbdzgnzmodhsrbf on 26 Aug 2026 via MCP.
-- This file is the repo-parity copy for supabase/migration (singular).
-- Idempotent: safe to re-run (IF NOT EXISTS / OR REPLACE / DROP ... IF EXISTS).
-- ============================================================

-- ---------- base helpers (no tms_ table refs) ----------
create or replace function public.tms_touch_updated_at() returns trigger
  language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;

create table if not exists public.tms_consignment_seq (
  year int primary key, last_no int not null default 0
);

create or replace function public.tms_assign_consignment_no() returns trigger
  language plpgsql security definer set search_path = public as $$
declare y int; n int;
begin
  if new.consignment_no is null or new.consignment_no = '' then
    y := extract(year from now())::int;
    insert into public.tms_consignment_seq(year, last_no) values (y, 1)
      on conflict (year) do update set last_no = public.tms_consignment_seq.last_no + 1
      returning last_no into n;
    new.consignment_no := 'UBF-C-' || y || '-' || lpad(n::text, 4, '0');
  end if;
  return new;
end; $$;

-- ---------- tables ----------
create table if not exists public.tms_depots (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  company_name text,
  address text, additional_info text,
  location_lat numeric, location_lng numeric,
  contact_name text, phone text, email text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tms_address_book (
  id uuid primary key default gen_random_uuid(),
  company_name text not null,
  address text, additional_info text,
  location_lat numeric, location_lng numeric,
  contact_name text, phone text, email text,
  additional_emails text[] default '{}',
  area_zone text check (area_zone in ('commercial','residential','rural')),
  milestones boolean not null default false,
  labels boolean not null default false,
  po_number text, reference text, port text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tms_drivers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique references auth.users(id) on delete set null,
  first_name text not null, last_name text not null,
  phone text unique,
  active boolean not null default true,
  home_depot_id uuid references public.tms_depots(id),
  current_registration text,
  last_lat numeric, last_lng numeric, last_seen_at timestamptz,
  last_source text check (last_source in ('mobile-app','navman')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tms_vehicles (
  id uuid primary key default gen_random_uuid(),
  registration_number text not null unique,
  description text,
  depot_id uuid references public.tms_depots(id),
  payload_kg numeric, cube_capacity_m3 numeric,
  has_tail_lift boolean not null default false,
  has_hiab boolean not null default false,
  is_reefer boolean not null default false,
  is_sideloader boolean not null default false,
  last_lat numeric, last_lng numeric, last_seen_at timestamptz,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tms_driver_vehicle (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid not null references public.tms_drivers(id) on delete cascade,
  vehicle_id uuid not null references public.tms_vehicles(id) on delete cascade,
  logged_on_at timestamptz not null default now(),
  logged_off_at timestamptz
);
create unique index if not exists tms_driver_vehicle_active_uidx
  on public.tms_driver_vehicle(driver_id) where logged_off_at is null;

create table if not exists public.tms_vehicle_positions (
  id bigint generated by default as identity primary key,
  vehicle_id uuid not null references public.tms_vehicles(id) on delete cascade,
  lat numeric not null, lng numeric not null,
  heading numeric, speed_kmh numeric,
  source text not null check (source in ('mobile-app','navman')),
  recorded_at timestamptz not null default now()
);
create index if not exists tms_vehicle_positions_veh_time_idx
  on public.tms_vehicle_positions(vehicle_id, recorded_at desc);

create table if not exists public.tms_consignments (
  id uuid primary key default gen_random_uuid(),
  consignment_no text unique,
  external_ref text,
  order_type text not null check (order_type in ('pick-up','drop-off','transfer')),
  depot_id uuid references public.tms_depots(id),
  status text not null default 'unassigned'
    check (status in ('draft','unassigned','assigned','inTransit','atDepot',
                      'assignedLeg2','inTransitLeg2','onHold','complete',
                      'checked_in','failed','inComplete','cancel','archived')),
  source text not null default 'manual' check (source in ('manual','booking','email','api')),
  booking_id uuid references public.bookings(id) on delete set null,
  job_unique bigint,
  shipment_ref text,
  trip_no int,
  leg_no int not null default 1,
  parent_consignment_id uuid references public.tms_consignments(id) on delete set null,
  sender_company text, sender_address text, sender_additional_info text,
  sender_contact text, sender_phone text, sender_email text,
  sender_additional_emails text[] default '{}',
  sender_lat numeric, sender_lng numeric,
  sender_area_zone text check (sender_area_zone in ('commercial','residential','rural')),
  receiver_company text, receiver_address text, receiver_additional_info text,
  receiver_contact text, receiver_phone text, receiver_email text,
  receiver_additional_emails text[] default '{}',
  receiver_lat numeric, receiver_lng numeric,
  preferred_pickup_at timestamptz, preferred_delivery_at timestamptz,
  estimated_delivery_at timestamptz, assigned_at timestamptz,
  po_number text, supplier_name text, reference text, delivery_instructions text,
  special_instructions jsonb not null default '[]'::jsonb,
  signature_required boolean not null default false,
  photo_pod_required boolean not null default false,
  urgent boolean not null default false,
  tail_lift_required boolean not null default false,
  customs_mpi boolean not null default false,
  fragile boolean not null default false,
  damaged boolean not null default false,
  labels_attached boolean not null default false,
  saturday_delivery boolean not null default false,
  temperature_control boolean not null default false,
  physically_scanned boolean not null default false,
  goods_type text not null default 'general' check (goods_type in ('general','dangerous')),
  dangerous_goods_reason text, temperature_control_reason text,
  calculate_volume_by text not null default 'unitType'
    check (calculate_volume_by in ('unitType','totalShipment')),
  assigned_driver_leg1 uuid references public.tms_drivers(id) on delete set null,
  assigned_driver_leg2 uuid references public.tms_drivers(id) on delete set null,
  assigned_vehicle_id uuid references public.tms_vehicles(id) on delete set null,
  total_items_scanned int not null default 0,
  total_items_scanned_leg2 int not null default 0,
  picked_up_at timestamptz, delivered_at timestamptz,
  penalty_seconds int not null default 0,
  driver_notes text, driver_notes_leg2 text,
  archived boolean not null default false,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists tms_consignments_status_idx on public.tms_consignments(status);
create index if not exists tms_consignments_depot_idx  on public.tms_consignments(depot_id);
create index if not exists tms_consignments_booking_idx on public.tms_consignments(booking_id);
create index if not exists tms_consignments_drv1_idx    on public.tms_consignments(assigned_driver_leg1);
create index if not exists tms_consignments_drv2_idx    on public.tms_consignments(assigned_driver_leg2);
create index if not exists tms_consignments_pickup_idx  on public.tms_consignments(preferred_pickup_at);
create index if not exists tms_consignments_archived_idx on public.tms_consignments(archived);

create table if not exists public.tms_consignment_cargo (
  id uuid primary key default gen_random_uuid(),
  consignment_id uuid not null references public.tms_consignments(id) on delete cascade,
  type text not null check (type in ('pallet','carton','crate','package','drum-gallon','bail-roll','piece')),
  units numeric, length_cm numeric, width_cm numeric, height_cm numeric,
  weight_kg numeric, marks text, total_cube_m3 numeric,
  sort_order int not null default 0
);
create index if not exists tms_cargo_consignment_idx on public.tms_consignment_cargo(consignment_id);

create table if not exists public.tms_checkin_sheets (
  id uuid primary key default gen_random_uuid(),
  consignment_id uuid references public.tms_consignments(id) on delete cascade,
  mode text check (mode in ('Air','Sea','Unknown')),
  consignee_company text,
  screened_by uuid references public.staff_users(user_id),
  screen_at timestamptz,
  known_shipper boolean not null default false,
  sufficient_packaging boolean not null default false,
  ipsm_pallet boolean not null default false,
  statement_of_content boolean not null default false,
  tamper_evident_form boolean not null default false,
  comments text,
  received_by uuid references public.staff_users(user_id),
  received_by_signature_url text,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists tms_checkin_consignment_idx on public.tms_checkin_sheets(consignment_id);

create table if not exists public.tms_pod (
  id uuid primary key default gen_random_uuid(),
  consignment_id uuid not null references public.tms_consignments(id) on delete cascade,
  leg_no int not null default 1,
  photos text[] default '{}',
  customer_signature_url text,
  customer_name text,
  rating text check (rating in ('sad','neutral','happy')),
  delivery_notes text,
  geo_lat numeric, geo_lng numeric,
  captured_at timestamptz not null default now(),
  captured_by uuid default auth.uid()
);
create index if not exists tms_pod_consignment_idx on public.tms_pod(consignment_id);

create table if not exists public.tms_dead_runs (
  id uuid primary key default gen_random_uuid(),
  consignment_id uuid not null references public.tms_consignments(id) on delete cascade,
  reason text, photos text[] default '{}',
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now()
);
create index if not exists tms_dead_runs_consignment_idx on public.tms_dead_runs(consignment_id);

create table if not exists public.tms_trips (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid references public.tms_drivers(id) on delete set null,
  vehicle_id uuid references public.tms_vehicles(id) on delete set null,
  depot_id uuid references public.tms_depots(id),
  trip_date date,
  status text not null default 'planned' check (status in ('planned','active','complete','cancelled')),
  stops jsonb not null default '[]'::jsonb,
  created_by uuid default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tms_events (
  id bigint generated by default as identity primary key,
  consignment_id uuid references public.tms_consignments(id) on delete cascade,
  event_code text not null,
  from_status text, to_status text,
  note text,
  actor uuid default auth.uid(),
  meta jsonb,
  created_at timestamptz not null default now()
);
create index if not exists tms_events_consignment_idx on public.tms_events(consignment_id, created_at desc);

create table if not exists public.tms_boards (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  created_by uuid default auth.uid(),
  filters jsonb not null default '[]'::jsonb,
  configuration jsonb,
  date_from text, date_to text,
  is_system boolean not null default false,
  deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- helper that references tms_drivers (created after table) ----------
create or replace function public.tms_driver_id() returns uuid
  language sql stable security definer set search_path = public as $$
  select id from public.tms_drivers where user_id = auth.uid() limit 1;
$$;

-- ---------- consignment number trigger ----------
drop trigger if exists tms_consignments_assign_no on public.tms_consignments;
create trigger tms_consignments_assign_no
  before insert on public.tms_consignments
  for each row execute function public.tms_assign_consignment_no();

-- ---------- updated_at triggers ----------
do $$
declare t text;
begin
  foreach t in array array['tms_depots','tms_address_book','tms_drivers','tms_vehicles',
                           'tms_consignments','tms_checkin_sheets','tms_trips','tms_boards']
  loop
    execute format('drop trigger if exists %I on public.%I;', t||'_touch', t);
    execute format('create trigger %I before update on public.%I for each row execute function public.tms_touch_updated_at();', t||'_touch', t);
  end loop;
end $$;

-- ---------- RLS enable ----------
do $$
declare t text;
begin
  foreach t in array array['tms_depots','tms_address_book','tms_drivers','tms_vehicles',
                           'tms_driver_vehicle','tms_vehicle_positions','tms_consignments',
                           'tms_consignment_cargo','tms_checkin_sheets','tms_pod','tms_dead_runs',
                           'tms_trips','tms_events','tms_boards','tms_consignment_seq']
  loop
    execute format('alter table public.%I enable row level security;', t);
  end loop;
end $$;

-- staff full access (pattern b)
do $$
declare t text;
begin
  foreach t in array array['tms_depots','tms_address_book','tms_drivers','tms_vehicles',
                           'tms_driver_vehicle','tms_vehicle_positions','tms_consignments',
                           'tms_consignment_cargo','tms_checkin_sheets','tms_pod','tms_dead_runs',
                           'tms_trips','tms_events','tms_boards']
  loop
    execute format('drop policy if exists staff_all on public.%I;', t);
    execute format('create policy staff_all on public.%I for all to authenticated using (public.is_staff()) with check (public.is_staff());', t);
  end loop;
end $$;

-- driver-scoped policies (mobile app)
drop policy if exists driver_read_consignments on public.tms_consignments;
create policy driver_read_consignments on public.tms_consignments
  for select to authenticated
  using (assigned_driver_leg1 = public.tms_driver_id() or assigned_driver_leg2 = public.tms_driver_id());

drop policy if exists driver_update_consignments on public.tms_consignments;
create policy driver_update_consignments on public.tms_consignments
  for update to authenticated
  using (assigned_driver_leg1 = public.tms_driver_id() or assigned_driver_leg2 = public.tms_driver_id())
  with check (assigned_driver_leg1 = public.tms_driver_id() or assigned_driver_leg2 = public.tms_driver_id());

drop policy if exists driver_read_cargo on public.tms_consignment_cargo;
create policy driver_read_cargo on public.tms_consignment_cargo
  for select to authenticated
  using (exists (select 1 from public.tms_consignments c where c.id = consignment_id
                 and (c.assigned_driver_leg1 = public.tms_driver_id() or c.assigned_driver_leg2 = public.tms_driver_id())));

drop policy if exists driver_write_pod on public.tms_pod;
create policy driver_write_pod on public.tms_pod
  for all to authenticated
  using (exists (select 1 from public.tms_consignments c where c.id = consignment_id
                 and (c.assigned_driver_leg1 = public.tms_driver_id() or c.assigned_driver_leg2 = public.tms_driver_id())))
  with check (exists (select 1 from public.tms_consignments c where c.id = consignment_id
                 and (c.assigned_driver_leg1 = public.tms_driver_id() or c.assigned_driver_leg2 = public.tms_driver_id())));

drop policy if exists driver_write_dead_runs on public.tms_dead_runs;
create policy driver_write_dead_runs on public.tms_dead_runs
  for all to authenticated
  using (exists (select 1 from public.tms_consignments c where c.id = consignment_id
                 and (c.assigned_driver_leg1 = public.tms_driver_id() or c.assigned_driver_leg2 = public.tms_driver_id())))
  with check (exists (select 1 from public.tms_consignments c where c.id = consignment_id
                 and (c.assigned_driver_leg1 = public.tms_driver_id() or c.assigned_driver_leg2 = public.tms_driver_id())));

drop policy if exists driver_write_events on public.tms_events;
create policy driver_write_events on public.tms_events
  for insert to authenticated
  with check (exists (select 1 from public.tms_consignments c where c.id = consignment_id
                 and (c.assigned_driver_leg1 = public.tms_driver_id() or c.assigned_driver_leg2 = public.tms_driver_id())));

drop policy if exists driver_read_own on public.tms_drivers;
create policy driver_read_own on public.tms_drivers
  for select to authenticated using (user_id = auth.uid());

drop policy if exists driver_insert_positions on public.tms_vehicle_positions;
create policy driver_insert_positions on public.tms_vehicle_positions
  for insert to authenticated with check (true);

-- ---------- grants (RLS still gates every row) ----------
grant select, insert, update, delete on
  public.tms_depots, public.tms_address_book, public.tms_drivers, public.tms_vehicles,
  public.tms_driver_vehicle, public.tms_vehicle_positions, public.tms_consignments,
  public.tms_consignment_cargo, public.tms_checkin_sheets, public.tms_pod,
  public.tms_dead_runs, public.tms_trips, public.tms_events, public.tms_boards
  to authenticated;
grant usage, select on all sequences in schema public to authenticated;

notify pgrst, 'reload schema';
