-- APPLIED LIVE 5 Oct 2026 via Supabase MCP. Repo parity only. DO NOT RE-RUN.
-- Migrations applied (in order):
--   container_dates_gate_time_v2        reporting.container_dates + v_container_dates + portal_container_dates gain gated_out_at
--   gate_out_notice_time                container_tracking_gate_out(): notice shows date + time
--   customer_tasks_autorun              customer_task_rules (confirm_delivery on, upload_docs off), customer_tasks_autorun(),
--                                       pg_cron 'customer-tasks-autorun' at :07 and :37
--   customer_tasks_autorun_stale_guard  estimated arrival only counts within 21 days; any prior confirm task blocks a new one
-- Bodies: select pg_get_functiondef('public.customer_tasks_autorun'::regproc), pg_get_viewdef('reporting.container_dates').
