-- 20260629_country_reference.sql
-- Prereq for SLI: ISO country dropdown + port->country auto-suggest.
-- LIVE in cpnkudbdzgnzmodhsrbf (applied via Supabase MCP). Repo record only.

-- 1. ISO 3166-1 countries (dropdown source)
create table if not exists public.countries (
  code text primary key,        -- ISO alpha-2
  name text not null
);

insert into public.countries (code, name) values
  ('AD','Andorra'),
  ('AE','United Arab Emirates'),
  ('AF','Afghanistan'),
  ('AG','Antigua and Barbuda'),
  ('AI','Anguilla'),
  ('AL','Albania'),
  ('AM','Armenia'),
  ('AO','Angola'),
  ('AQ','Antarctica'),
  ('AR','Argentina'),
  ('AS','American Samoa'),
  ('AT','Austria'),
  ('AU','Australia'),
  ('AW','Aruba'),
  ('AX','Aland Islands'),
  ('AZ','Azerbaijan'),
  ('BA','Bosnia and Herzegovina'),
  ('BB','Barbados'),
  ('BD','Bangladesh'),
  ('BE','Belgium'),
  ('BF','Burkina Faso'),
  ('BG','Bulgaria'),
  ('BH','Bahrain'),
  ('BI','Burundi'),
  ('BJ','Benin'),
  ('BL','Saint Barthelemy'),
  ('BM','Bermuda'),
  ('BN','Brunei Darussalam'),
  ('BO','Bolivia'),
  ('BQ','Bonaire, Sint Eustatius and Saba'),
  ('BR','Brazil'),
  ('BS','Bahamas'),
  ('BT','Bhutan'),
  ('BV','Bouvet Island'),
  ('BW','Botswana'),
  ('BY','Belarus'),
  ('BZ','Belize'),
  ('CA','Canada'),
  ('CC','Cocos (Keeling) Islands'),
  ('CD','Congo, Democratic Republic of the'),
  ('CF','Central African Republic'),
  ('CG','Congo'),
  ('CH','Switzerland'),
  ('CI','Cote d''Ivoire'),
  ('CK','Cook Islands'),
  ('CL','Chile'),
  ('CM','Cameroon'),
  ('CN','China'),
  ('CO','Colombia'),
  ('CR','Costa Rica'),
  ('CU','Cuba'),
  ('CV','Cabo Verde'),
  ('CW','Curacao'),
  ('CX','Christmas Island'),
  ('CY','Cyprus'),
  ('CZ','Czechia'),
  ('DE','Germany'),
  ('DJ','Djibouti'),
  ('DK','Denmark'),
  ('DM','Dominica'),
  ('DO','Dominican Republic'),
  ('DZ','Algeria'),
  ('EC','Ecuador'),
  ('EE','Estonia'),
  ('EG','Egypt'),
  ('EH','Western Sahara'),
  ('ER','Eritrea'),
  ('ES','Spain'),
  ('ET','Ethiopia'),
  ('FI','Finland'),
  ('FJ','Fiji'),
  ('FK','Falkland Islands'),
  ('FM','Micronesia'),
  ('FO','Faroe Islands'),
  ('FR','France'),
  ('GA','Gabon'),
  ('GB','United Kingdom'),
  ('GD','Grenada'),
  ('GE','Georgia'),
  ('GF','French Guiana'),
  ('GG','Guernsey'),
  ('GH','Ghana'),
  ('GI','Gibraltar'),
  ('GL','Greenland'),
  ('GM','Gambia'),
  ('GN','Guinea'),
  ('GP','Guadeloupe'),
  ('GQ','Equatorial Guinea'),
  ('GR','Greece'),
  ('GS','South Georgia and the South Sandwich Islands'),
  ('GT','Guatemala'),
  ('GU','Guam'),
  ('GW','Guinea-Bissau'),
  ('GY','Guyana'),
  ('HK','Hong Kong'),
  ('HM','Heard Island and McDonald Islands'),
  ('HN','Honduras'),
  ('HR','Croatia'),
  ('HT','Haiti'),
  ('HU','Hungary'),
  ('ID','Indonesia'),
  ('IE','Ireland'),
  ('IL','Israel'),
  ('IM','Isle of Man'),
  ('IN','India'),
  ('IO','British Indian Ocean Territory'),
  ('IQ','Iraq'),
  ('IR','Iran'),
  ('IS','Iceland'),
  ('IT','Italy'),
  ('JE','Jersey'),
  ('JM','Jamaica'),
  ('JO','Jordan'),
  ('JP','Japan'),
  ('KE','Kenya'),
  ('KG','Kyrgyzstan'),
  ('KH','Cambodia'),
  ('KI','Kiribati'),
  ('KM','Comoros'),
  ('KN','Saint Kitts and Nevis'),
  ('KP','Korea, North'),
  ('KR','Korea, South'),
  ('KW','Kuwait'),
  ('KY','Cayman Islands'),
  ('KZ','Kazakhstan'),
  ('LA','Laos'),
  ('LB','Lebanon'),
  ('LC','Saint Lucia'),
  ('LI','Liechtenstein'),
  ('LK','Sri Lanka'),
  ('LR','Liberia'),
  ('LS','Lesotho'),
  ('LT','Lithuania'),
  ('LU','Luxembourg'),
  ('LV','Latvia'),
  ('LY','Libya'),
  ('MA','Morocco'),
  ('MC','Monaco'),
  ('MD','Moldova'),
  ('ME','Montenegro'),
  ('MF','Saint Martin'),
  ('MG','Madagascar'),
  ('MH','Marshall Islands'),
  ('MK','North Macedonia'),
  ('ML','Mali'),
  ('MM','Myanmar'),
  ('MN','Mongolia'),
  ('MO','Macao'),
  ('MP','Northern Mariana Islands'),
  ('MQ','Martinique'),
  ('MR','Mauritania'),
  ('MS','Montserrat'),
  ('MT','Malta'),
  ('MU','Mauritius'),
  ('MV','Maldives'),
  ('MW','Malawi'),
  ('MX','Mexico'),
  ('MY','Malaysia'),
  ('MZ','Mozambique'),
  ('NA','Namibia'),
  ('NC','New Caledonia'),
  ('NE','Niger'),
  ('NF','Norfolk Island'),
  ('NG','Nigeria'),
  ('NI','Nicaragua'),
  ('NL','Netherlands'),
  ('NO','Norway'),
  ('NP','Nepal'),
  ('NR','Nauru'),
  ('NU','Niue'),
  ('NZ','New Zealand'),
  ('OM','Oman'),
  ('PA','Panama'),
  ('PE','Peru'),
  ('PF','French Polynesia'),
  ('PG','Papua New Guinea'),
  ('PH','Philippines'),
  ('PK','Pakistan'),
  ('PL','Poland'),
  ('PM','Saint Pierre and Miquelon'),
  ('PN','Pitcairn'),
  ('PR','Puerto Rico'),
  ('PS','Palestine'),
  ('PT','Portugal'),
  ('PW','Palau'),
  ('PY','Paraguay'),
  ('QA','Qatar'),
  ('RE','Reunion'),
  ('RO','Romania'),
  ('RS','Serbia'),
  ('RU','Russian Federation'),
  ('RW','Rwanda'),
  ('SA','Saudi Arabia'),
  ('SB','Solomon Islands'),
  ('SC','Seychelles'),
  ('SD','Sudan'),
  ('SE','Sweden'),
  ('SG','Singapore'),
  ('SH','Saint Helena'),
  ('SI','Slovenia'),
  ('SJ','Svalbard and Jan Mayen'),
  ('SK','Slovakia'),
  ('SL','Sierra Leone'),
  ('SM','San Marino'),
  ('SN','Senegal'),
  ('SO','Somalia'),
  ('SR','Suriname'),
  ('SS','South Sudan'),
  ('ST','Sao Tome and Principe'),
  ('SV','El Salvador'),
  ('SX','Sint Maarten'),
  ('SY','Syrian Arab Republic'),
  ('SZ','Eswatini'),
  ('TC','Turks and Caicos Islands'),
  ('TD','Chad'),
  ('TF','French Southern Territories'),
  ('TG','Togo'),
  ('TH','Thailand'),
  ('TJ','Tajikistan'),
  ('TK','Tokelau'),
  ('TL','Timor-Leste'),
  ('TM','Turkmenistan'),
  ('TN','Tunisia'),
  ('TO','Tonga'),
  ('TR','Turkiye'),
  ('TT','Trinidad and Tobago'),
  ('TV','Tuvalu'),
  ('TW','Taiwan'),
  ('TZ','Tanzania'),
  ('UA','Ukraine'),
  ('UG','Uganda'),
  ('UM','United States Minor Outlying Islands'),
  ('US','United States'),
  ('UY','Uruguay'),
  ('UZ','Uzbekistan'),
  ('VA','Holy See'),
  ('VC','Saint Vincent and the Grenadines'),
  ('VE','Venezuela'),
  ('VG','Virgin Islands (British)'),
  ('VI','Virgin Islands (U.S.)'),
  ('VN','Viet Nam'),
  ('VU','Vanuatu'),
  ('WF','Wallis and Futuna'),
  ('WS','Samoa'),
  ('YE','Yemen'),
  ('YT','Mayotte'),
  ('ZA','South Africa'),
  ('ZM','Zambia'),
  ('ZW','Zimbabwe')
on conflict (code) do update set name = excluded.name;

-- 2. port -> country
alter table public.ports add column if not exists country_code text references public.countries(code);

-- 2a. sea ports: first 2 chars of 5-char UNLOCODE = ISO country
update public.ports
set country_code = upper(left(code,2))
where kind = 'sea' and length(code) = 5
  and upper(left(code,2)) in (select code from public.countries);

-- 2b. air ports: exact IATA -> ISO map (all 158 codes in data)
update public.ports p
set country_code = m.cc
from (values
  ('ACC','GH'),
  ('AKL','NZ'),
  ('ALA','KZ'),
  ('ALC','ES'),
  ('AMD','IN'),
  ('AMS','NL'),
  ('APW','WS'),
  ('ASU','PY'),
  ('ATQ','IN'),
  ('AUH','AE'),
  ('BAH','BH'),
  ('BJS','CN'),
  ('BKK','TH'),
  ('BLR','IN'),
  ('BNE','AU'),
  ('BOD','FR'),
  ('BOG','CO'),
  ('BOM','IN'),
  ('BRU','BE'),
  ('BTH','ID'),
  ('BTS','SK'),
  ('BWN','BN'),
  ('CAI','EG'),
  ('CAN','CN'),
  ('CCU','IN'),
  ('CDG','FR'),
  ('CGK','ID'),
  ('CGO','CN'),
  ('CGX','US'),
  ('CHC','NZ'),
  ('CMB','LK'),
  ('CNF','BR'),
  ('CNS','AU'),
  ('COK','IN'),
  ('COR','AR'),
  ('CPT','ZA'),
  ('CXI','KI'),
  ('DEL','IN'),
  ('DIL','TL'),
  ('DMM','SA'),
  ('DOH','QA'),
  ('DUB','IE'),
  ('DUR','ZA'),
  ('DUS','DE'),
  ('DWC','AE'),
  ('DXB','AE'),
  ('EBB','UG'),
  ('EBL','IQ'),
  ('EZE','AR'),
  ('FBM','CD'),
  ('FCO','IT'),
  ('FRA','DE'),
  ('FUN','TV'),
  ('GRU','BR'),
  ('HAM','DE'),
  ('HAN','VN'),
  ('HEL','FI'),
  ('HGH','CN'),
  ('HIR','SB'),
  ('HKG','HK'),
  ('HLG','US'),
  ('HND','JP'),
  ('HOU','US'),
  ('HYD','IN'),
  ('IAH','US'),
  ('ICN','KR'),
  ('IKA','IR'),
  ('INU','NR'),
  ('ISB','PK'),
  ('IST','TR'),
  ('IUE','NU'),
  ('JED','SA'),
  ('JFK','US'),
  ('JNB','ZA'),
  ('KEF','IS'),
  ('KHI','PK'),
  ('KTW','PL'),
  ('KUL','MY'),
  ('LAE','PG'),
  ('LAX','US'),
  ('LGW','GB'),
  ('LHE','PK'),
  ('LHR','GB'),
  ('LIM','PE'),
  ('LIS','PT'),
  ('LON','GB'),
  ('LOS','NG'),
  ('LRD','US'),
  ('LUN','ZM'),
  ('MAA','IN'),
  ('MAD','ES'),
  ('MAJ','MH'),
  ('MCI','US'),
  ('MCT','OM'),
  ('MDE','CO'),
  ('MEL','AU'),
  ('MEX','MX'),
  ('MIA','US'),
  ('MLE','MV'),
  ('MNL','PH'),
  ('MRU','MU'),
  ('MXP','IT'),
  ('NAN','FJ'),
  ('NBO','KE'),
  ('NGB','CN'),
  ('NOU','NC'),
  ('NPE','NZ'),
  ('NRT','JP'),
  ('OPO','PT'),
  ('ORD','US'),
  ('OTP','RO'),
  ('PDX','US'),
  ('PEK','CN'),
  ('PER','AU'),
  ('PHL','US'),
  ('PNG','CN'),
  ('POM','PG'),
  ('PPG','AS'),
  ('PPT','PF'),
  ('PRG','CZ'),
  ('PVG','CN'),
  ('RAR','CK'),
  ('REC','BR'),
  ('RTM','NL'),
  ('RUH','SA'),
  ('SCL','CL'),
  ('SEA','US'),
  ('SGN','VN'),
  ('SHA','CN'),
  ('SHJ','AE'),
  ('SIN','SG'),
  ('SJO','CR'),
  ('SLC','US'),
  ('STR','DE'),
  ('SYD','AU'),
  ('SZX','CN'),
  ('TAE','KR'),
  ('TAO','CN'),
  ('TBS','GE'),
  ('TBU','TO'),
  ('TLL','EE'),
  ('TNR','MG'),
  ('TPE','TW'),
  ('TRW','KI'),
  ('TSN','CN'),
  ('VIE','AT'),
  ('VLC','ES'),
  ('VLI','VU'),
  ('WAW','PL'),
  ('WLG','NZ'),
  ('WRO','PL'),
  ('XMN','CN'),
  ('YEG','CA'),
  ('YOW','CA'),
  ('YUL','CA'),
  ('YVR','CA'),
  ('YYZ','CA'),
  ('ZRH','CH')
) as m(iata, cc)
where p.kind = 'air' and p.code = m.iata;

-- 3. read access for staff app
grant select on public.countries to authenticated;

-- 4. sanity: surface any port still unmapped (should be 0 for known data)
do $$
declare n int;
begin
  select count(*) into n from public.ports where country_code is null;
  raise notice 'ports without country_code: %', n;
end $$;
